### ISSUE TITLE
package menteslibres.net/gosexy/yaml: unrecognized import path

### ISSUE THREAD

**Issue by quicksandznzn** [gosexy/yaml#3]
package menteslibres.net/gosexy/yaml: unrecognized import path

**Comment by GeoWonk** [comment]
I assume this project is largely abandoned, however I got it installed by cloning the repository locally into the gopath, editing but files so `menteslibres.net/` became `github.com/` and using `go get yaml`

**Comment by quicksandznzn** [comment]
alright
